language: julia
dist: trusty

os:
  - linux
  - osx

julia:
  - 1.3
  - 1.4
  - nightly

branches:
  only:
    - master
    - /^release-.*/

notifications:
  email: false

cache:
  directories:
  - $HOME/.ccache
  - $HOME/.julia/registries # can we cache all of .julia?

matrix:
  allow_failures:
  - julia: nightly

jobs:
  include:
    - stage: "Tests" # implicit first stage
    - stage: "Coverage"
      julia: 1.0
      os: linux
      after_success: # Intentionally rerun tests
        - julia -e 'using Pkg; cd(Pkg.dir("MPIClusterManagers")); Pkg.add("Coverage")'
        - julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
        - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder())'
